### ISSUE TITLE
Opening: Responding 'nothing' to "what is something fun you did today" ends the conversation.

### ISSUE THREAD

**Issue by harshita-sahijwani** [emora-chat/emora#135]
I tried testing the bot on developer console (dev version), and I think 'nothing' is being identified as a stop-intent utterance.

**Comment by sefinch** [comment]
This is an issue I had seen and investigated a while ago. I added logic to ignore text values of "nothing" when it maps to Amazon.CancelIntent in order to keep the conversation going. So, now, this patch works in Live and we only see the problem in Beta because we do not get ASR results for Beta conversations (and, thus, no text value for CancelIntents).

**Comment by harshita-sahijwani** [comment]
just to be sure, do we have logic to handle "never mind" or "forget it" as well?
