### ISSUE TITLE
Conflict of Sports and Dialogue Manager, handling "I don't care"

### ISSUE THREAD

**Issue by Programmer01001101** [emora-chat/emora#148]
The sports component currently asks "what do you think of the NBA shut down?", some users respond "I don't care", which the user refers to he/she doesn't care about the "NBA shut down" event.  However, 'I don't care'  is caught by the dialogue manager and suggests the user to completely leave sports component and talk about other topics. I wonder if there is a way to fix this . The following is an example from the logs:

E: I am so sad that nba got shutdown. what do you think about it?
 U: I honestly don't care 
E: You seem to want to change topics. I am happy to do so with you.   So, there is a lot of new music that has come out recently.    What band do you enjoy listening to? 
 U: billie eilish 

Although completely switching the topic does not affect the conversation flow too much, I wonder if there is a better way of handling this.  (the user from the above example still gave us a rating of 4.0 )

**Comment by sefinch** [comment]
Part of the problem is that most components don't handle an "i dont care" response and people get stuck in a topic, which is why we handled it on a higher level. It might be possible to exclude sports from this higher level handling without too much trouble, or to modify the detection to fit cases like this better, but I'll have to look into it.
