### ISSUE TITLE
Movies: index into list error

### ISSUE THREAD

**Issue by sefinch** [emora-chat/emora#162]
Conversation Id: 48c50182bf80770fe7ff3ebd6f979d6309002cca4cf1f4e24eb9b02b4836ddc0
Session Id: amzn1.echo-api.session.4379a5a0-45ef-4a07-ba50-61aa7f5100f4

[2020-04-08T04:33:22] E: Yeah, I thought as much.   Ok. tell me, what was the last movie you liked?  ((external) movies)
[2020-04-08T04:33:32]  U: birds of prey  (IntentRequest)
[2020-04-08T04:33:32] E: Well, ok. I think watching movies is a great way to relax and have fun.  ((dialogue_manager) movies)

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=cobot-stack-BotServicemovies-container-log;stream=37dbaabedb5e01b7395ba8f923febed4d48935194f98ea734926bcad6e32417e;refid=35376127360502466041969565153313506046444128031337807872;reftime=1586320414209

**Comment by sergey-volokhin** [comment]
Are you sure this is the latest update? I have fixed this error in the previous pull request, and it works fine locally

**Comment by sefinch** [comment]
I merged in your pull request and it was pushed to Live yesterday. There are no outstanding pull requests currently. Dev is up to date and mainline is up to date with dev, I just tried to pull and merge both. So, I would say, look at the movies code in the mainline branch, let me know if it looks wrong and we can go from there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sergey-volokhin** [comment]
I found an error and I am going to fix it this night, but for it to work, I need you to merge my changes asap, because fixing consists of 3 steps: updating the code, deleting and updating all my elasticsearch indexes, and then updating the code again. in that order. 
i will put deletion on timer, so it will happen at ~4-5 am. do you think you could merge my first pull request before then? and second pull request in the morning?
