### ISSUE TITLE
Switching to other components

### ISSUE THREAD

**Issue by Programmer01001101** [emora-chat/emora#203]
Hello,

While I was testing locally, I found   "lets talk about []" sometimes does not during the conversation. The following is one of the situations.  Could you talk a look?
<img width="721" alt="Screen Shot 2020-05-20 at 23 10 04" src="https://user-images.githubusercontent.com/32470722/82521103-c28d6c00-9af3-11ea-9598-909830354088.png">

**Comment by sefinch** [comment]
I dont really know why the v r one isnt working when you test it in interactive mode. It works if we do it in Dev and Live, both typed and in spoken language like how real users will do it.

We don't have "pet" as a valid option for "lets talk about X" because it isn't grammatical. It would be "pets" instead. But we can add it in for coverage, it is possible it occurs in ASR errors on the spoken input so it is a good failsafe.
