### ISSUE TITLE
Music component is slowing down

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#31]
Please check if the music component is slower than what it should be.

**Comment by sergey-volokhin** [comment]
it is indeed slower than it's supposed to be. this is due to me having to scan dynamodb table at each turn, which takes a lot of time. 
this will be fixed when i start using entity linker that Harshita made. I will try to do that after 16th (systems final). 

in the meantime, do you think we should disable the music component completely to not anger users? or continue with a slow one?

**Comment by jdchoi77** [comment]
Let's disable it until you fix it; let me change the milestone to the 16th then. @sfillwo, could you please take the music component out for now?

**Comment by sefinch** [comment]
this was fixed a while ago
