### ISSUE TITLE
Sports: response to "What sports do you like" is not handled correctly

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#45]
No matter what the user responses to "What sports do you like?", it says either

1. "We share the same hobby" if the answer was "basketball"
1. "That's good to hear" for anything else and proceed with the script.

The 2nd case should be handled more robustly.  For example, if the user says "let's talk about movie", it should switch to the movie component right away.

**Comment by Programmer01001101** [comment]
If a user's favorite sports is not basketball, Emora will ask him if he watches basketball at all. If the user plays(or watches) basketball,  Emora will continue with the sports component. Otherwise, the user will be redirected to other components.

Situation 1 : 

- Emora: I love sports. My favorite sport is basketball. What is your favorite sport?
- User: Soccer
- Emora: That is a great sport. I am sorry I only watch basketball. Do you play or watch basketball?
- User: Yes
- Emora: Wow, I am glad that we share same hobby! I love watching NBA. Do you watch NBA?


Situation 2:

- Emora: I love sports. My favorite sport is basketball. What is your favorite sport?
- User: Soccer
- Emora: That is a great sport. I am sorry I only watch basketball. Do you play or watch basketball?
- User: No.
- Emora: Ok. I am sorry that I could only talk about basketball in the sports domain for now. Do you want to talk about something else? We could talk about recent movies or news if you like.
- User:  movies
- Emora: Ok. I can give general movie-related information, tell you movie plot and reviews, check for fresh movies in the theatres, and more. So, tell me, what was the last movie you liked?
