### ISSUE TITLE
Sports: the conversation gets redirected to the very beginning

### ISSUE THREAD

**Issue by jdchoi77** [emora-chat/emora#49]
```
I: let's chat (OtherIntent, Phatic)
O: Hi this is an Alexa Prize Socialbot. What name would you like to me to call you? (openingsm)
I: tyler (Acceptance, Phatic)
O: Ok I am very glad to meet you tyler . its pretty early where I am . How are you today? (openingsm)
I: i'm tired (General_ChatIntent, Phatic)
O: I was hoping for a better day for you. If you don't mind talking about it what happened? (openingsm)
I: no bad day (TopicSwitch, no)
O: Some days are worse than others but I know you will have good days coming. What would you like to talk about today? (openingsm)
I: the latest news (Information_RequestIntent, Politics)
O: i dont recall if i have thought of the latest news recently. why is that on your mind? (fallbacktransitions)
I: because the president (Acceptance, Phatic)
O: Allright, so, do you want to talk about something else, like movies or sports? (pets)
I: yes let's talk about sports (Information_RequestIntent, Sports)
O: I love sports. My favorite sport is basketball. What is your favorite sport? (nba)
I: football (Information_DeliveryIntent, Sports)
O: Oh, My friend told me that football is one of the most popular sportss in the united states. Let me guess, are you from the united states? (nba)
I: yes (Acceptance, Sports)
O: Haha, gotcha. Let us continue to talk about sports. I love playing basketball.  Do you play or watch basketball? (nba)
I: no i like football (Information_DeliveryIntent, Sports)
O: Ok. I am sorry that I could only talk about basketball in the sports domain for now. Do you want to talk about something else? We could talk about recent movies or news if you like. (nba)
I: let's talk about football (Information_RequestIntent, Sports)
O: Hi this is an Alexa Prize Socialbot. I am happy to be talking to you. How are you today? (openingsm)
I: awesome (Acceptance, Phatic)
O: Hmm I'm not sure what you mean. What would you like to talk about today? (openingsm)
I: football (Information_RequestIntent, Sports)
O: i dont think i have thought of football in the last few days. can you tell me more about your opinion on it? (fallbacktransitions)
```

The sports component is redirecting the conversation to the opening component so the user repeats the entire conversation again; this needs to be fixed right away.

**Comment by sefinch** [comment]
This may not be a problem with Sports. Ruixiang and Sonny, let me know if you find a problem with Sports that seems to be causing this; otherwise, I will be looking into the opening itself.

**Comment by Programmer01001101** [comment]
I believe part of the reason was that sports component didn't handle the 'ending state' of the component properly and I have fixed that. However, I found out that after exiting our component, the movie component could no longer be triggered properly.

Here is a sample conversation :  

- Emora : I love sports. My favorite sport is basketball. What is your favorite sport?
- User: football
- Emora: Oh, My friend told me that football is one of the most popular sportss in the united states. Let me guess, are you from the united states?
- User:  yes
- Emora: Haha, gotcha. Let us continue to talk about sports. I love playing basketball.  Do you play or watch basketball?
- User:  no , let's talk about football
- Emora: Ok. I am sorry that I could only talk about basketball in the sports domain for now. Do you want to talk about something else? We could talk about recent movies or news if you like.
- User: no, i want to talk about football
- Emora:  I am sorry that I only have knowledge about basketball for the moment. I will try my best to learn your favorite sports in the future. Besides basketball, I could also talk about recent movies or update you with recent news.
- User: ok... let's talk about movies
- Emora:  Gotcha. What would you like to talk about today?
- User: movies

 **_Emora: i believe you are interested in movies. why is that in your thoughts?_**
   **_User: i love movies, let's talk about movies
 Emora:  Allright, so, do you want to talk about something else, like movies or sports?
 User:  movies
 Emora: Allright, so, do you want to talk about something else, like movies or sports?
 User : movies
Emora: Allright, so, do you want to talk about something else, like movies or sports_**

- User: Sports
- Emora: I am sorry that I only have knowledge about basketball for the moment. I will try my best to learn your favorite sports in the future. Besides basketball, I could also talk about recent movies or update you with recent news.

**Comment by sefinch** [comment]
This should be fixed, I pushed a patch over the weekend.
